from __future__ import annotations

import argparse
from dataclasses import dataclass
import os
import re
from pathlib import Path

from shared.artifact_paths import analysis_path, generated_tasks_dir
from shared.task_utils import (
    TASK_FILE_RE,
    find_task_by_marker,
    load_task_records,
    next_task_number,
    select_next_task,
    slugify,
)
from shared.target_repo_config import resolve_target_repo_config

FILE_BLOCK_RE = re.compile(
    r"===FILE:\s*(TASK-\d{3}-[a-z0-9-]+\.md)\s*===\n(.*?)\n===END===",
    re.DOTALL,
)


@dataclass(frozen=True)
class PlannerPhaseResult:
    task_artifact: tuple[Path, str] | None
    continue_to_implementation: bool


@dataclass(frozen=True)
class MVPTaskCandidate:
    title: str
    slug: str
    objective: str
    scope: tuple[str, ...]
    out_of_scope: tuple[str, ...]
    acceptance_criteria: tuple[str, ...]
    grounding: tuple[str, ...]
    dependencies: tuple[str, ...] = ()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the planner phase against this repository."
    )
    parser.add_argument(
        "goal",
        nargs="?",
        help="Human goal for the local file-based planner phase.",
    )
    parser.add_argument(
        "--repo",
        default=".",
        help="Target repository path. Defaults to current repository.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the planner output without writing files.",
    )
    return parser.parse_args()


def parse_file_blocks(text: str) -> list[tuple[str, str]]:
    return [(name, body.strip() + "\n") for name, body in FILE_BLOCK_RE.findall(text)]


def build_task_markdown(task_id: int, goal: str) -> str:
    task_code = f"TASK-{task_id:03d}"
    slug = slugify(goal)

    return f"""# {task_code} Planner Follow-up: {goal}

## Status
todo

## Priority
high

## Objective
Translate the latest analyst findings into concrete implementation work aligned with this goal: {goal}

## Scope
- Use `agents/analysis/repo-analysis.md` as the planning input
- Define one focused implementation slice that can be completed in a single cycle
- Keep task boundaries explicit and implementation-ready

## Out of Scope
- Implementing the task itself
- Introducing unrelated refactors

## Acceptance Criteria
- Backlog task is specific and executable
- Acceptance criteria are testable
- Dependencies are explicitly listed

## Dependencies
- None

## Notes
Generated by `scripts/run_planner.py` (planner phase).
Slug: `{slug}`
"""


def build_generated_task_markdown(task_id: int, candidate: MVPTaskCandidate) -> str:
    task_code = f"TASK-{task_id:03d}"
    scope_text = "\n".join(f"- {item}" for item in candidate.scope)
    out_of_scope_text = "\n".join(f"- {item}" for item in candidate.out_of_scope)
    acceptance_text = "\n".join(f"- {item}" for item in candidate.acceptance_criteria)
    dependencies_text = (
        "\n".join(f"- {item}" for item in candidate.dependencies)
        if candidate.dependencies
        else "None"
    )
    grounding_text = "\n".join(f"- {item}" for item in candidate.grounding)

    return f"""# {task_code} {candidate.title}

## Status
todo

## Priority
high

## Objective
{candidate.objective}

## Scope
{scope_text}

## Out of Scope
{out_of_scope_text}

## Acceptance Criteria
{acceptance_text}

## Dependencies
{dependencies_text}

## Notes
Generated by `scripts/run_planner.py` because the backlog was exhausted during a promptless MVP run.
Grounding:
{grounding_text}
Slug: `{candidate.slug}`
"""


def read_text_if_exists(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def slug_task_statuses(workspace_root: Path, target_name: str, slug: str) -> list[str]:
    suffix = f"-{slug}.md"
    return [
        record.status
        for record in load_task_records(workspace_root, target_name)
        if record.path.name.endswith(suffix)
    ]


def should_skip_candidate(workspace_root: Path, target_name: str, slug: str) -> bool:
    statuses = slug_task_statuses(workspace_root, target_name, slug)
    return any(status in {"todo", "in-progress", "done"} for status in statuses)


def detect_commit_push_gap(workspace_root: Path, target_name: str, mvp_text: str, _analysis_text: str) -> MVPTaskCandidate | None:
    run_developer_text = read_text_if_exists(workspace_root / "scripts" / "run_developer.py").lower()
    run_reviewer_text = read_text_if_exists(workspace_root / "scripts" / "run_reviewer.py").lower()
    mvp_requires = "commit and push" in mvp_text.lower() or (
        "push" in mvp_text.lower() and "commit" in mvp_text.lower()
    )
    developer_has_git_automation = bool(
        re.search(r"git\s+(commit|push)", run_developer_text)
    ) or ("subprocess" in run_developer_text and "git" in run_developer_text)
    reviewer_uses_commit_hash = "commit hash" in run_reviewer_text or "pushed commit" in run_reviewer_text

    if not mvp_requires or developer_has_git_automation:
        return None

    if should_skip_candidate(workspace_root, target_name, "automate-developer-commit-push-in-mvp-mode"):
        return None

    return MVPTaskCandidate(
        title="Automate developer commit and push in MVP mode",
        slug="automate-developer-commit-push-in-mvp-mode",
        objective=(
            "Extend the developer execution path so completed MVP tasks are committed, pushed, "
            "and handed off with the pushed commit hash for reviewer follow-up."
        ),
        scope=(
            "Update `scripts/run_developer.py` so successful `--execute` runs create a focused git commit for the selected task changes",
            "Push the new commit with the existing repository git remote configuration and capture the pushed commit hash",
            "Include the pushed commit hash in the developer handoff artifact so downstream phases can reference the exact committed state",
            "Adjust reviewer/task handoff logic only as needed so reviewer follow-up can use the pushed commit reference",
        ),
        out_of_scope=(
            "Feature-branch or pull-request workflow changes outside the MVP direct-to-main path",
            "Deployment automation or merge orchestration",
            "Broad refactors unrelated to developer commit/push handoff behavior",
        ),
        acceptance_criteria=(
            "`scripts/run_developer.py --execute` performs focused commit/push steps after successful task implementation",
            "The developer handoff artifact records the pushed commit hash for the selected task",
            "Reviewer inputs can reference the pushed commit instead of relying only on the local worktree",
            "Verification includes at least one dry-run or guarded command path showing the commit/push workflow without silently skipping it",
        ),
        grounding=(
            "`docs/mvp.md` requires developer commit/push behavior and reviewer evaluation of the pushed commit in MVP mode",
            "`agents/analysis/repo-analysis.md` still flags later workflow integration gaps and heuristic planning risk",
            "Repository evidence: `scripts/run_developer.py` applies file changes but does not run git commit/push automation yet",
            (
                "Repository evidence: `scripts/run_reviewer.py`"
                + (" already references pushed commits in wording only" if reviewer_uses_commit_hash else " does not yet consume a pushed commit hash from developer output")
            ),
        ),
    )


def detect_repo_state_gap(workspace_root: Path, target_name: str, mvp_text: str, _analysis_text: str) -> MVPTaskCandidate | None:
    run_cycle_text = read_text_if_exists(workspace_root / "scripts" / "run_cycle.py")
    env_example_text = read_text_if_exists(workspace_root / ".env.example")
    mvp_requires = "repository state" in mvp_text.lower() and "mvp_done" in mvp_text.lower()
    repo_state_is_supported = (
        "TARGET_REPOSITORY_STATE" in run_cycle_text
        or "TARGET_REPO_STATE" in run_cycle_text
        or "target-repository-state" in run_cycle_text.lower()
        or "repo-state" in run_cycle_text.lower()
    )

    if not mvp_requires or repo_state_is_supported:
        return None

    if should_skip_candidate(workspace_root, target_name, "add-explicit-target-repository-state-handling"):
        return None

    return MVPTaskCandidate(
        title="Add explicit target repository state handling to the runner",
        slug="add-explicit-target-repository-state-handling",
        objective=(
            "Introduce explicit target repository state handling so the local runner can enforce different behavior for `MVP`, `MVP_DONE`, `TEST`, and `PROD`."
        ),
        scope=(
            "Add a tracked runner/config input for target repository state instead of relying on hidden `.env` conventions",
            "Teach `scripts/run_cycle.py` to read and surface the active repository state during orchestration",
            "Define the minimum behavior differences for `MVP`, `MVP_DONE`, `TEST`, and `PROD` in the local runner path",
            "Update the relevant workflow docs only as needed to match the implemented state-aware runner behavior",
        ),
        out_of_scope=(
            "Production deployment automation",
            "Full policy enforcement for every future environment rule",
            "Infrastructure provisioning or observability services",
        ),
        acceptance_criteria=(
            "The runner accepts an explicit target repository state input without requiring a hidden `.env`-only workflow",
            "`scripts/run_cycle.py` surfaces and uses the configured state in at least one orchestration decision",
            "The supported states include `MVP`, `MVP_DONE`, `TEST`, and `PROD`",
            "Verification demonstrates the state-aware runner path with a dry-run command",
        ),
        grounding=(
            "`docs/mvp.md` defines an explicit repository state model with `MVP`, `MVP_DONE`, `TEST`, and `PROD`",
            "`agents/analysis/repo-analysis.md` still calls out workflow integration gaps that should be turned into concrete runner behavior",
            "Repository evidence: `scripts/run_cycle.py` currently has no explicit target repository state handling",
            (
                "Repository evidence: `.env.example` "
                + ("already contains unrelated runtime secrets but no target repository state entry" if "TARGET_REPO_STATE" not in env_example_text else "does not provide the state-aware runner behavior required by the MVP")
            ),
        ),
    )


def detect_autonomous_mvp_loop_gap(workspace_root: Path, target_name: str, mvp_text: str, _analysis_text: str) -> MVPTaskCandidate | None:
    run_cycle_text = read_text_if_exists(workspace_root / "scripts" / "run_cycle.py").lower()
    mvp_requires = "loop repeats automatically" in mvp_text.lower() and "mvp_done" in mvp_text.lower()
    autonomous_loop_supported = "continue automatically" in run_cycle_text or "mvp_done" in run_cycle_text

    if not mvp_requires or autonomous_loop_supported:
        return None

    if should_skip_candidate(workspace_root, target_name, "add-mvp-mode-autonomous-continuation"):
        return None

    return MVPTaskCandidate(
        title="Add MVP-mode autonomous continuation and stop conditions",
        slug="add-mvp-mode-autonomous-continuation",
        objective=(
            "Teach the orchestrator to continue automatically in `MVP` mode until `MVP_DONE` or a clean stop condition is reached."
        ),
        scope=(
            "Extend the runner/orchestrator flow so it can continue across tasks while the repository state is `MVP`",
            "Add visible stop-condition artifacts for exhausted backlog, blocked execution, and repeated validation failure",
            "Keep the automation bounded to the local workflow without introducing distributed orchestration",
        ),
        out_of_scope=(
            "Production schedulers, deployment systems, or background worker fleets",
            "Infrastructure provisioning",
            "Changing branch strategy outside the MVP bootstrap flow",
        ),
        acceptance_criteria=(
            "The orchestrator can continue beyond a single task when operating in `MVP` mode",
            "The loop stops cleanly with a visible reason when no grounded next task or safe continuation path exists",
            "Verification demonstrates the autonomous continuation decision path with a dry-run or controlled local run",
        ),
        grounding=(
            "`docs/mvp.md` says the loop should continue automatically in `MVP` mode until `MVP_DONE` or a stop condition is hit",
            "`agents/analysis/repo-analysis.md` identifies later workflow integration points as an active gap",
            "Repository evidence: `scripts/run_cycle.py` runs a single phase chain per invocation and stops without state-aware continuation logic",
        ),
    )


def select_next_mvp_candidate(workspace_root: Path, target_name: str, mvp_text: str, analysis_text: str) -> MVPTaskCandidate | None:
    detectors = (
        detect_commit_push_gap,
        detect_repo_state_gap,
        detect_autonomous_mvp_loop_gap,
    )
    for detector in detectors:
        candidate = detector(workspace_root, target_name, mvp_text, analysis_text)
        if candidate is not None:
            return candidate
    return None


def generate_next_mvp_task(
    workspace_root: Path,
    target_name: str,
    dry_run: bool,
) -> PlannerPhaseResult:
    current_analysis_path = analysis_path(workspace_root, target_name)
    mvp_path = workspace_root / "docs" / "mvp.md"
    missing_inputs = [
        str(path.relative_to(workspace_root))
        for path in (mvp_path, current_analysis_path)
        if not path.exists()
    ]
    if missing_inputs:
        print(
            "Planner stopped cleanly: unable to generate the next MVP task because "
            f"required inputs are missing: {', '.join(missing_inputs)}."
        )
        return PlannerPhaseResult(task_artifact=None, continue_to_implementation=False)

    analysis_text = current_analysis_path.read_text(encoding="utf-8")
    mvp_text = mvp_path.read_text(encoding="utf-8")
    candidate = select_next_mvp_candidate(
        workspace_root=workspace_root,
        target_name=target_name,
        mvp_text=mvp_text,
        analysis_text=analysis_text,
    )

    if candidate is None:
        print(
            "Planner stopped cleanly: unable to derive a grounded next MVP task from "
            f"`docs/mvp.md` and `{current_analysis_path.relative_to(workspace_root)}`."
        )
        return PlannerPhaseResult(task_artifact=None, continue_to_implementation=False)

    tasks_dir = generated_tasks_dir(workspace_root, target_name)
    tasks_dir.mkdir(parents=True, exist_ok=True)
    task_id = next_task_number(tasks_dir)
    target = tasks_dir / f"TASK-{task_id:03d}-{candidate.slug}.md"
    content = build_generated_task_markdown(task_id=task_id, candidate=candidate)

    if dry_run:
        print(f"[dry-run] Would write planner task: {target}")
        print(content)
        print(
            "[dry-run] Planner generated a new MVP task for human review. "
            "Stopping before developer execution."
        )
        return PlannerPhaseResult(
            task_artifact=(target, content),
            continue_to_implementation=False,
        )

    target.write_text(content, encoding="utf-8")
    print(f"Planner generated new MVP task for human review: {target}")
    print("Stopping before developer execution so a human can review the new task.")
    return PlannerPhaseResult(
        task_artifact=(target, content),
        continue_to_implementation=False,
    )


def run_planner_phase(
    goal: str | None,
    repo_root: Path,
    workspace_root: Path,
    target_name: str,
    dry_run: bool,
) -> PlannerPhaseResult:
    if not goal:
        try:
            task_path, task_content = select_next_task(workspace_root, target_name)
        except FileNotFoundError:
            return generate_next_mvp_task(
                workspace_root=workspace_root,
                target_name=target_name,
                dry_run=dry_run,
            )

        message = f"Planner selected existing backlog task: {task_path}"
        if dry_run:
            print(f"[dry-run] {message}")
        else:
            print(message)
        return PlannerPhaseResult(
            task_artifact=(task_path, task_content),
            continue_to_implementation=True,
        )

    current_analysis_path = analysis_path(workspace_root, target_name)
    if not current_analysis_path.exists() and not dry_run:
        raise FileNotFoundError(
            f"Planner phase requires {current_analysis_path.relative_to(workspace_root)}. Run analyst first."
        )

    tasks_dir = generated_tasks_dir(workspace_root, target_name)
    tasks_dir.mkdir(parents=True, exist_ok=True)

    marker = f"Planner Follow-up: {goal}"
    existing = find_task_by_marker(tasks_dir, marker)

    if existing is None:
        task_id = next_task_number(tasks_dir)
        target = tasks_dir / f"TASK-{task_id:03d}-{slugify(goal)}.md"
    else:
        task_path, _task_content = existing
        match = TASK_FILE_RE.match(task_path.name)
        task_id = int(match.group(1)) if match else next_task_number(tasks_dir)
        target = task_path

    content = build_task_markdown(task_id=task_id, goal=goal)

    if dry_run:
        print(f"[dry-run] Would write planner task: {target}")
        print(content)
        return PlannerPhaseResult(
            task_artifact=(target, content),
            continue_to_implementation=True,
        )

    target.write_text(content, encoding="utf-8")
    print(f"Planner task ready: {target}")
    return PlannerPhaseResult(
        task_artifact=(target, content),
        continue_to_implementation=True,
    )


def run_llm_planner(repo_path: Path) -> list[Path]:
    from llm import run_prompt

    workspace_root = Path(".").resolve()
    target_name = repo_path.name
    current_analysis_path = analysis_path(workspace_root, target_name)
    planner_prompt_path = workspace_root / "prompts" / "agents" / "planner.md"
    tasks_dir = generated_tasks_dir(workspace_root, target_name)

    analysis_text = current_analysis_path.read_text(encoding="utf-8")
    planner_prompt = planner_prompt_path.read_text(encoding="utf-8")

    instruction = """
Return one or more task files in this exact format:
===FILE: TASK-###-short-description.md===
<full markdown content of that task file>
===END===

Rules:
- Use lowercase kebab-case for short-description.
- Use unique task numbers that do not conflict with existing files.
- Only output these file blocks.
""".strip()

    existing_files = "\n".join(sorted(path.name for path in tasks_dir.glob("TASK-*.md")))

    full_prompt = (
        f"{planner_prompt}\n\n"
        f"Existing task files:\n{existing_files}\n\n"
        f"Analysis:\n{analysis_text}\n\n"
        f"{instruction}"
    )

    output = run_prompt(full_prompt)
    blocks = parse_file_blocks(output)

    if not blocks:
        number = next_task_number(tasks_dir)
        fallback_name = f"TASK-{number:03d}-planner-generated-task.md"
        blocks = [(fallback_name, output.strip() + "\n")]

    tasks_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    used_names: set[str] = set()
    next_number = next_task_number(tasks_dir)

    for name, body in blocks:
        if not TASK_FILE_RE.match(name) or name in used_names or (tasks_dir / name).exists():
            name = f"TASK-{next_number:03d}-planner-generated-task.md"
            next_number += 1

        used_names.add(name)
        path = tasks_dir / name
        path.write_text(body, encoding="utf-8")
        written.append(path)

    return written


def main() -> None:
    args = parse_args()
    if args.goal:
        repo_path = Path(args.repo).resolve()
        run_planner_phase(
            goal=args.goal,
            repo_root=repo_path,
            workspace_root=Path(".").resolve(),
            target_name=repo_path.name,
            dry_run=args.dry_run,
        )
        return

    from dotenv import load_dotenv

    load_dotenv()
    workspace_root = Path(".").resolve()
    target_config = resolve_target_repo_config(
        workspace_root,
        cli_repo=None,
        cli_state=None,
        config_name=os.getenv("TARGET_REPOSITORY_CONFIG"),
    )
    repo_path = target_config.path
    written = run_llm_planner(repo_path)

    print("Wrote task files:")
    for path in written:
        print(f"- {path}")


if __name__ == "__main__":
    main()
