from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
import os
import re
from pathlib import Path

from shared.artifact_paths import analysis_path, generated_tasks_dir
from shared.task_utils import (
    TASK_FILE_RE,
    extract_section,
    find_task_by_marker,
    load_task_records,
    next_task_number,
    select_next_task,
    slugify,
)
from shared.target_repo_config import resolve_target_repo_config

FILE_BLOCK_RE = re.compile(
    r"===FILE:\s*(TASK-\d{3}-[a-z0-9-]+\.md)\s*===\n(.*?)\n===END===",
    re.DOTALL,
)


@dataclass(frozen=True)
class PlannerPhaseResult:
    task_artifact: tuple[Path, str] | None
    continue_to_implementation: bool


@dataclass(frozen=True)
class MVPTaskCandidate:
    title: str
    slug: str
    objective: str
    scope: tuple[str, ...]
    out_of_scope: tuple[str, ...]
    acceptance_criteria: tuple[str, ...]
    grounding: tuple[str, ...]
    dependencies: tuple[str, ...] = ()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the planner phase against this repository."
    )
    parser.add_argument(
        "goal",
        nargs="?",
        help="Human goal for the local file-based planner phase.",
    )
    parser.add_argument(
        "--repo",
        default=".",
        help="Target repository path. Defaults to current repository.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the planner output without writing files.",
    )
    return parser.parse_args()


def parse_file_blocks(text: str) -> list[tuple[str, str]]:
    return [(name, body.strip() + "\n") for name, body in FILE_BLOCK_RE.findall(text)]


def build_task_markdown(task_id: int, goal: str) -> str:
    task_code = f"TASK-{task_id:03d}"
    slug = slugify(goal)

    return f"""# {task_code} Planner Follow-up: {goal}

## Status
todo

## Priority
high

## Objective
Translate the latest analyst findings into concrete implementation work aligned with this goal: {goal}

## Scope
- Use `agents/analysis/repo-analysis.md` as the planning input
- Define one focused implementation slice that can be completed in a single cycle
- Keep task boundaries explicit and implementation-ready

## Out of Scope
- Implementing the task itself
- Introducing unrelated refactors

## Acceptance Criteria
- Backlog task is specific and executable
- Acceptance criteria are testable
- Dependencies are explicitly listed

## Dependencies
- None

## Notes
Generated by `scripts/run_planner.py` (planner phase).
Slug: `{slug}`
"""


def build_generated_task_markdown(task_id: int, candidate: MVPTaskCandidate) -> str:
    task_code = f"TASK-{task_id:03d}"
    scope_text = "\n".join(f"- {item}" for item in candidate.scope)
    out_of_scope_text = "\n".join(f"- {item}" for item in candidate.out_of_scope)
    acceptance_text = "\n".join(f"- {item}" for item in candidate.acceptance_criteria)
    dependencies_text = (
        "\n".join(f"- {item}" for item in candidate.dependencies)
        if candidate.dependencies
        else "None"
    )
    grounding_text = "\n".join(f"- {item}" for item in candidate.grounding)

    return f"""# {task_code} {candidate.title}

## Status
todo

## Priority
high

## Objective
{candidate.objective}

## Scope
{scope_text}

## Out of Scope
{out_of_scope_text}

## Acceptance Criteria
{acceptance_text}

## Dependencies
{dependencies_text}

## Notes
Generated by `scripts/run_planner.py` because the backlog was exhausted during an AI-backed MVP gap evaluation.
Grounding:
{grounding_text}
Slug: `{candidate.slug}`
"""


def read_text_if_exists(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def slug_task_statuses(workspace_root: Path, target_name: str, slug: str) -> list[str]:
    suffix = f"-{slug}.md"
    return [
        record.status
        for record in load_task_records(workspace_root, target_name)
        if record.path.name.endswith(suffix)
    ]


def existing_objectives(workspace_root: Path, target_name: str) -> set[str]:
    return {
        extract_section(record.content, "Objective").strip().lower()
        for record in load_task_records(workspace_root, target_name)
        if extract_section(record.content, "Objective").strip()
    }


def should_skip_candidate(
    workspace_root: Path,
    target_name: str,
    slug: str,
    objective: str | None = None,
) -> bool:
    statuses = slug_task_statuses(workspace_root, target_name, slug)
    if any(status in {"todo", "in-progress", "done"} for status in statuses):
        return True
    if objective is None:
        return False
    return objective.strip().lower() in existing_objectives(workspace_root, target_name)


def detect_commit_push_gap(workspace_root: Path, target_name: str, mvp_text: str, _analysis_text: str) -> MVPTaskCandidate | None:
    run_developer_text = read_text_if_exists(workspace_root / "scripts" / "run_developer.py").lower()
    run_reviewer_text = read_text_if_exists(workspace_root / "scripts" / "run_reviewer.py").lower()
    mvp_requires = "commit and push" in mvp_text.lower() or (
        "push" in mvp_text.lower() and "commit" in mvp_text.lower()
    )
    developer_has_git_automation = bool(
        re.search(r"git\s+(commit|push)", run_developer_text)
    ) or ("subprocess" in run_developer_text and "git" in run_developer_text)
    reviewer_uses_commit_hash = "commit hash" in run_reviewer_text or "pushed commit" in run_reviewer_text

    objective = (
        "Extend the developer execution path so completed MVP tasks are committed, pushed, "
        "and handed off with the pushed commit hash for reviewer follow-up."
    )
    if not mvp_requires or developer_has_git_automation:
        return None

    if should_skip_candidate(
        workspace_root,
        target_name,
        "automate-developer-commit-push-in-mvp-mode",
        objective,
    ):
        return None

    return MVPTaskCandidate(
        title="Automate developer commit and push in MVP mode",
        slug="automate-developer-commit-push-in-mvp-mode",
        objective=objective,
        scope=(
            "Update `scripts/run_developer.py` so successful `--execute` runs create a focused git commit for the selected task changes",
            "Push the new commit with the existing repository git remote configuration and capture the pushed commit hash",
            "Include the pushed commit hash in the developer handoff artifact so downstream phases can reference the exact committed state",
            "Adjust reviewer/task handoff logic only as needed so reviewer follow-up can use the pushed commit reference",
        ),
        out_of_scope=(
            "Feature-branch or pull-request workflow changes outside the MVP direct-to-main path",
            "Deployment automation or merge orchestration",
            "Broad refactors unrelated to developer commit/push handoff behavior",
        ),
        acceptance_criteria=(
            "`scripts/run_developer.py --execute` performs focused commit/push steps after successful task implementation",
            "The developer handoff artifact records the pushed commit hash for the selected task",
            "Reviewer inputs can reference the pushed commit instead of relying only on the local worktree",
            "Verification includes at least one dry-run or guarded command path showing the commit/push workflow without silently skipping it",
        ),
        grounding=(
            "`docs/mvp.md` requires developer commit/push behavior and reviewer evaluation of the pushed commit in MVP mode",
            "`agents/analysis/repo-analysis.md` still flags later workflow integration gaps and heuristic planning risk",
            "Repository evidence: `scripts/run_developer.py` applies file changes but does not run git commit/push automation yet",
            (
                "Repository evidence: `scripts/run_reviewer.py`"
                + (" already references pushed commits in wording only" if reviewer_uses_commit_hash else " does not yet consume a pushed commit hash from developer output")
            ),
        ),
    )


def detect_repo_state_gap(workspace_root: Path, target_name: str, mvp_text: str, _analysis_text: str) -> MVPTaskCandidate | None:
    run_cycle_text = read_text_if_exists(workspace_root / "scripts" / "run_cycle.py")
    env_example_text = read_text_if_exists(workspace_root / ".env.example")
    mvp_requires = "repository state" in mvp_text.lower() and "mvp_done" in mvp_text.lower()
    repo_state_is_supported = (
        "TARGET_REPOSITORY_STATE" in env_example_text
        or "target repository state" in run_cycle_text.lower()
        or "mvp_done" in run_cycle_text.lower()
    )

    objective = (
        "Add explicit target-repository state handling so the workflow can adapt behavior across MVP, "
        "MVP_DONE, TEST, and PROD without relying on hidden conventions."
    )
    if not mvp_requires or repo_state_is_supported:
        return None

    if should_skip_candidate(
        workspace_root,
        target_name,
        "add-explicit-target-repository-state-handling",
        objective,
    ):
        return None

    return MVPTaskCandidate(
        title="Add explicit target repository state handling",
        slug="add-explicit-target-repository-state-handling",
        objective=objective,
        scope=(
            "Introduce a tracked configuration or runtime property for the active target repository state",
            "Update the runner/orchestration entry points to read and enforce the configured state",
            "Ensure MVP mode can continue automatically while non-MVP states expose stricter stop conditions",
            "Document any required configuration surface in code-facing artifacts only as needed to support the runner change",
        ),
        out_of_scope=(
            "Deploy-time infrastructure policy enforcement beyond state plumbing",
            "A full production approval framework",
            "Unrelated workflow redesign outside state-aware behavior",
        ),
        acceptance_criteria=(
            "The active target repository state can be configured explicitly instead of relying only on ad-hoc environment conventions",
            "Runner logic can detect at least MVP and MVP_DONE and adapt continuation behavior accordingly",
            "State handling is wired through the main execution path used for iterative runs",
            "Verification demonstrates the configured state changes runner behavior in a controlled way",
        ),
        grounding=(
            "`docs/mvp.md` requires an explicit repository state model with MVP, MVP_DONE, TEST, and PROD",
            "`agents/analysis/repo-analysis.md` calls out missing workflow integration points in the current thin slice",
            "Repository evidence: current runner scripts do not yet enforce a first-class target repository state model",
        ),
    )


def parse_candidate_dict(payload: object) -> MVPTaskCandidate | None:
    if not isinstance(payload, dict):
        return None

    required_str_fields = ("title", "slug", "objective")
    for field in required_str_fields:
        value = payload.get(field)
        if not isinstance(value, str) or not value.strip():
            return None

    def parse_list(name: str) -> tuple[str, ...] | None:
        value = payload.get(name)
        if not isinstance(value, list) or not value:
            return None
        items = tuple(str(item).strip() for item in value if str(item).strip())
        return items if items else None

    scope = parse_list("scope")
    out_of_scope = parse_list("out_of_scope")
    acceptance_criteria = parse_list("acceptance_criteria")
    grounding = parse_list("grounding")
    if not all((scope, out_of_scope, acceptance_criteria, grounding)):
        return None

    dependencies_value = payload.get("dependencies", [])
    if dependencies_value == "None":
        dependencies: tuple[str, ...] = ()
    elif isinstance(dependencies_value, list):
        dependencies = tuple(
            str(item).strip() for item in dependencies_value if str(item).strip()
        )
    else:
        dependencies = ()

    slug = slugify(str(payload["slug"]))
    if not slug:
        return None

    return MVPTaskCandidate(
        title=str(payload["title"]).strip(),
        slug=slug,
        objective=str(payload["objective"]).strip(),
        scope=scope,
        out_of_scope=out_of_scope,
        acceptance_criteria=acceptance_criteria,
        grounding=grounding,
        dependencies=dependencies,
    )


def collect_repository_evidence(workspace_root: Path, target_repo_root: Path) -> str:
    evidence: list[str] = []
    candidates = [
        "README.md",
        "AGENTS.md",
        "docs/mvp.md",
        "docs/agent-workflow.md",
        "docs/agent-handoff-contract.md",
        "scripts/run_cycle.py",
        "scripts/run_developer.py",
        "scripts/run_reviewer.py",
        "scripts/run_tester.py",
        "scripts/run_planner.py",
        "scripts/run_analyst.py",
    ]

    for relative in candidates:
        path = workspace_root / relative
        if not path.exists():
            continue
        text = read_text_if_exists(path).strip()
        if not text:
            continue
        preview = text[:4000]
        if len(text) > 4000:
            preview += "\n... [truncated]"
        evidence.append(f"--- WORKSPACE FILE: {relative} ---\n{preview}")

    if target_repo_root != workspace_root:
        for relative in ("README.md", "docs/mvp.md", "docs/target-repo-context.md"):
            path = target_repo_root / relative
            if not path.exists():
                continue
            text = read_text_if_exists(path).strip()
            if not text:
                continue
            preview = text[:2500]
            if len(text) > 2500:
                preview += "\n... [truncated]"
            evidence.append(f"--- TARGET FILE: {relative} ---\n{preview}")

    return "\n\n".join(evidence) if evidence else "(No additional repository evidence collected.)"


def run_llm_planner(
    *,
    workspace_root: Path,
    target_repo_root: Path,
    target_name: str,
    mvp_text: str,
    analysis_text: str,
) -> MVPTaskCandidate | None:
    from llm import run_prompt

    prompt = f"""
You are the planner agent for a repository automation workflow.

Goal:
Evaluate whether there is one remaining grounded MVP gap for the active target repository and, if so, propose exactly one implementation-ready backlog task.

Constraints:
- You may propose AT MOST one task.
- Base the task on the provided MVP definition, target-scoped repo analysis, and repository evidence.
- Do not propose generic cleanup, vague improvements, or multi-task epics.
- If MVP appears complete or you cannot justify a grounded next task, return {{"decision":"stop","reason":"<brief reason>"}}.
- If you propose a task, return JSON only with this shape:
  {{
    "decision": "task",
    "task": {{
      "title": "...",
      "slug": "...",
      "objective": "...",
      "scope": ["...", "..."],
      "out_of_scope": ["...", "..."],
      "acceptance_criteria": ["...", "..."],
      "dependencies": ["None"] or ["..."],
      "grounding": ["...", "..."]
    }}
  }}
- The slug must be short, kebab-case, and repository-specific enough to avoid collisions.
- The task must be a focused implementation slice that could reasonably fit in one development cycle.

MVP definition:
--- docs/mvp.md ---
{mvp_text or "(missing)"}

Target-scoped analysis:
--- agents/{target_name}/analysis/repo-analysis.md ---
{analysis_text or "(missing)"}

Current repository evidence:
{collect_repository_evidence(workspace_root, target_repo_root)}
""".strip()

    raw_output = run_prompt(prompt).strip()

    try:
        payload = json.loads(raw_output)
    except json.JSONDecodeError:
        return None

    if payload.get("decision") != "task":
        return None

    return parse_candidate_dict(payload.get("task"))


def plan_next_mvp_task(
    workspace_root: Path,
    target_repo_root: Path,
    target_name: str,
) -> MVPTaskCandidate | None:
    mvp_text = read_text_if_exists(workspace_root / "docs" / "mvp.md")
    analysis_text = read_text_if_exists(analysis_path(workspace_root, target_name))

    heuristic_candidates = (
        detect_commit_push_gap(workspace_root, target_name, mvp_text, analysis_text),
        detect_repo_state_gap(workspace_root, target_name, mvp_text, analysis_text),
    )
    for candidate in heuristic_candidates:
        if candidate is not None:
            return candidate

    ai_candidate = run_llm_planner(
        workspace_root=workspace_root,
        target_repo_root=target_repo_root,
        target_name=target_name,
        mvp_text=mvp_text,
        analysis_text=analysis_text,
    )
    if ai_candidate is None:
        return None
    if should_skip_candidate(
        workspace_root,
        target_name,
        ai_candidate.slug,
        ai_candidate.objective,
    ):
        return None
    return ai_candidate


def write_candidate_task(
    workspace_root: Path,
    target_name: str,
    candidate: MVPTaskCandidate,
    dry_run: bool,
) -> Path:
    tasks_dir = generated_tasks_dir(workspace_root, target_name)
    task_id = next_task_number(tasks_dir)
    path = tasks_dir / f"TASK-{task_id:03d}-{candidate.slug}.md"
    content = build_generated_task_markdown(task_id, candidate)

    if dry_run:
        print(f"[dry-run] Would write planner task: {path}")
        print(content)
        return path

    tasks_dir.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"Generated planner task: {path}")
    return path


def run_planner_phase(
    goal: str | None,
    target_repo_root: Path,
    workspace_root: Path,
    target_name: str,
    dry_run: bool,
) -> PlannerPhaseResult:
    try:
        selected_path, selected_content = select_next_task(workspace_root, target_name)
    except FileNotFoundError:
        selected_path = None
        selected_content = None

    if selected_path is not None and selected_content is not None:
        print(f"Selected existing task: {selected_path}")
        return PlannerPhaseResult(
            task_artifact=(selected_path, selected_content),
            continue_to_implementation=True,
        )

    candidate = plan_next_mvp_task(
        workspace_root=workspace_root,
        target_repo_root=target_repo_root,
        target_name=target_name,
    )
    if candidate is None:
        print("No grounded next task found; stopping planner cleanly.")
        return PlannerPhaseResult(task_artifact=None, continue_to_implementation=False)

    task_path = write_candidate_task(
        workspace_root=workspace_root,
        target_name=target_name,
        candidate=candidate,
        dry_run=dry_run,
    )
    content = build_generated_task_markdown(
        int(TASK_FILE_RE.match(task_path.name).group(1)),
        candidate,
    )
    return PlannerPhaseResult(
        task_artifact=(task_path, content),
        continue_to_implementation=False,
    )


def main() -> None:
    args = parse_args()
    if args.goal:
        workspace_root = Path(".").resolve()
        target_repo_root = Path(args.repo).resolve()
        target_name = target_repo_root.name
        run_planner_phase(
            goal=args.goal,
            target_repo_root=target_repo_root,
            workspace_root=workspace_root,
            target_name=target_name,
            dry_run=args.dry_run,
        )
        return

    from dotenv import load_dotenv

    load_dotenv()
    workspace_root = Path(".").resolve()
    target_config = resolve_target_repo_config(
        workspace_root,
        cli_repo=None,
        cli_state=None,
        config_name=os.getenv("TARGET_REPOSITORY_CONFIG"),
    )
    result = run_planner_phase(
        goal="Advance the target repository toward MVP completion",
        target_repo_root=target_config.path,
        workspace_root=workspace_root,
        target_name=target_config.name,
        dry_run=False,
    )
    if result.task_artifact is None:
        return
    print(f"Planner selected: {result.task_artifact[0]}")


if __name__ == "__main__":
    main()
